name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${00d27a8e-84f6-4d7a-93e4-b3bbf5cb316b}" | docker login -u "${dbartnickicl}" --password docker.io
        docker build . --file Dockerfile --tag docker.io/${dbartnickicl}/${task2}:$GITHUB_SHA
        docker push docker.io/${dbartnickicl}/${task2}:$GITHUB_SHA
